language: python

python: "3.6"

install:
  - pip install vim-vint
  - (if ! test -d $HOME/vim-$VIM_VERSION/bin; then
    git clone https://github.com/vim/vim $HOME/vim &&
    cd $HOME/vim &&
    git checkout v$VIM_VERSION &&
    ./configure --prefix=$HOME/vim-$VIM_VERSION &&
    make &&
    make install;
    fi)

cache:
  directories:
    - $HOME/vim-$VIM_VERSION

env:
  - VIM_VERSION=8.2.0000
  - VIM_VERSION=8.1.0000
  - VIM_VERSION=8.0.0000
  - VIM_VERSION=7.4

script:
  - vint vimrc
  - vint rc/vimplug_rc.vim
  - sh bin/vimplug_installer.sh
  - vim --version
  - vim +":so test/test.vim"
